# Generated by Django 6.0.1 on 2026-01-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioritization', '0002_task_delete_studenttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='credit_weight',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
