# Generated by Django 6.0.1 on 2026-01-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioritization', '0003_alter_task_credit_weight_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
