# Generated by Django 6.0.1 on 2026-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioritization', '0004_task_is_done_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade_impact',
            field=models.IntegerField(default=5),
        ),
    ]
