# Generated by Django 6.0.1 on 2026-03-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioritization', '0005_task_grade_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_name',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
